org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false

kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096m

# Set to true in CI to fail the build on compiler warnings.
warningsAsErrors=false
